install.packages("dplyr",repos='http://cran.us.r-project.org')
install.packages("tidyr",repos='http://cran.us.r-project.org')
install.packages("expss",repos='http://cran.us.r-project.org')
install.packages("spatstat",repos='http://cran.us.r-project.org')
install.packages("Hmisc",repos='http://cran.us.r-project.org')

library(dplyr)
library(tidyr)
library(stats)
library(expss)
library(spatstat)
library(Hmisc)
